version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
